version: '3'

services:
  jhooq-springboot-container:
    image: cc-project-docker-compose:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/cc-project-container
    ports:
      - "8080-8100:8080"