apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cc-project
  template:
    metadata:
      labels:
        app: cc-project
    spec:
      containers:
        - name: cc-project-container
          image: abhijitthikekar/cc-project:cc-project
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: cc-project
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: cc-project
